version: '3.8'

services:
  php:
    image: php:8.1.0RC6-alpine
    restart: 'no'
    volumes:
      - .:/app
    working_dir: /app

  snowplow_micro:
    image: snowplow/snowplow-micro:1.2.1
    volumes:
      - ./tests/Snowplow/:/config/
    ports:
      - "9090:9090"
    command: '--collector-config /config/micro.conf --iglu /config/iglu.json'
